export default [
  {
    id: 1,
    title: "r/mildlyinteresting",
    description: "blah blah",
    coverImg: "logo.svg",
    stats: {
      members: 20,
      online: 6,
    },
    isJoined: false,
  },
  {
    id: 2,
    title: "r/funny",
    description: "blah blah haha",
    coverImg: "funny.png",
    stats: {
      members: 200,
      online: 60,
    },
    isJoined: true,
  },
  {
    id: 3,
    title: "r/space",
    description: "blah blah space",
    coverImg: "logo.svg",
    stats: {
      members: 203,
      online: 63,
    },
    isJoined: false,
  },
  {
    id: 1,
    title: "r/mildlyinteresting",
    description: "blah blah",
    coverImg: "logo.svg",
    stats: {
      members: 20,
      online: 6,
    },
    isJoined: false,
  },
  {
    id: 2,
    title: "r/funny",
    description: "blah blah haha",
    coverImg: "funny.png",
    stats: {
      members: 200,
      online: 60,
    },
    isJoined: true,
  },
  {
    id: 3,
    title: "r/space",
    description: "blah blah space",
    coverImg: "logo.svg",
    stats: {
      members: 203,
      online: 63,
    },
    isJoined: false,
  },
  {
    id: 1,
    title: "r/mildlyinteresting",
    description: "blah blah",
    coverImg: "logo.svg",
    stats: {
      members: 20,
      online: 6,
    },
    isJoined: false,
  },
  {
    id: 2,
    title: "r/funny",
    description: "blah blah haha",
    coverImg: "funny.png",
    stats: {
      members: 200,
      online: 60,
    },
    isJoined: true,
  },
  {
    id: 3,
    title: "r/space",
    description: "blah blah space",
    coverImg: "logo.svg",
    stats: {
      members: 203,
      online: 63,
    },
    isJoined: false,
  },
  {
    id: 1,
    title: "r/mildlyinteresting",
    description: "blah blah",
    coverImg: "logo.svg",
    stats: {
      members: 20,
      online: 6,
    },
    isJoined: false,
  },
  {
    id: 2,
    title: "r/funny",
    description: "blah blah haha",
    coverImg: "funny.png",
    stats: {
      members: 200,
      online: 60,
    },
    isJoined: true,
  },
  {
    id: 3,
    title: "r/space",
    description: "blah blah space",
    coverImg: "logo.svg",
    stats: {
      members: 203,
      online: 63,
    },
    isJoined: false,
  },
  {
    id: 1,
    title: "r/mildlyinteresting",
    description: "blah blah",
    coverImg: "logo.svg",
    stats: {
      members: 20,
      online: 6,
    },
    isJoined: false,
  },
  {
    id: 2,
    title: "r/funny",
    description: "blah blah haha",
    coverImg: "funny.png",
    stats: {
      members: 200,
      online: 60,
    },
    isJoined: true,
  },
  {
    id: 3,
    title: "r/space",
    description: "blah blah space",
    coverImg: "logo.svg",
    stats: {
      members: 203,
      online: 63,
    },
    isJoined: false,
  },
];
